on: [workflow_dispatch, push]

name: Build Workflow

# Create an environment variable named DOTNET_VERSION
# and set it as "6.0.x"
env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use

# Defines a single job named "build"
jobs:
  build:
    
    # When the workflow runs, this is the name that is logged
    # This job will run one time, once for each "os" defined
    runs-on: ${{ matrix.os }}
    #environment: 'dev'
    strategy:
      matrix:
        os: [windows-latest]   
    steps:
       # 1) Check out the source code so that the workflow can access it.
      - uses: actions/checkout@v3
      
      # 2) Set up the .NET CLI environment for the workflow to use.
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # 3) Restore the dependencies and tools of a project or solution.
      - name: Install dependencies
        run: dotnet restore
      
      # 4) Build a project or solution and all of its dependencies.
      - name: Build
        run: dotnet build --no-restore

      #- name: Test
      #  run: 
